[package]
name = "mandelbrot_set"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
rayon = "1.10.0"
libc = "0.2.155"
rand = "0.9.0-alpha.1"
clap = { version = "4.5.4", features = ["derive"] }

[build-dependencies]
cc = "1.0.98"